[package]
name = "os-link-checker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
