[package]
name = "mash-release"
version = "1.2.15"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
mash-hal = { path = "../../crates/mash-hal" }
semver = "1.0"
toml_edit = "0.22"
